name: notebook2
dependencies:
  - python=3.7
  - requests
  - flask
  - pip
  - pip:
      - kubernetes==9.*
      - Flask_Sockets==0.2.*
      - libsass==0.18.*
      - authlib==0.12.*
      - pymysql==0.9.*
      - aiohttp
      - aiohttp-jinja2
      - uvloop
      - ./hailjwt
